name: tutors
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"
dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.5.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_storage: ^11.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_form_builder: ^9.0.0
  fluttertoast: ^8.2.1
  form_builder_validators: ^9.0.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_sign_in: ^6.0.2
  http: ^1.1.0
  image_cropper: ^5.0.0
  image_picker: ^0.8.7+3
  injectable: ^2.1.0
  injectable_generator: ^2.1.4
  internet_connection_checker: ^1.0.0+1
  logger: ^1.2.2
  lottie: ^2.3.1
  modal_bottom_sheet: ^3.0.0-pre
  path_provider: ^2.0.14
  shared_preferences: ^2.1.0
  skeletons: ^0.0.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/lotties/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
